

#define tris__cs_3210		TRISB,TRISB3	
#define tris__reset_3210	TRISA,TRISA0	
#define tris__int_3210		TRISC,TRISC2	
#define tris_pcm_3210_pclk	TRISA,TRISA4	
#define tris_pcm_3210_drx	TRISA,TRISA3	
#define tris_pcm_3210_dtx	TRISA,TRISA2	
#define	tris_pcm_3210_fsync	TRISA,TRISA1	
#define _reset_3210		LATA,LATA0
#define	_cs_3210		LATB,LATB3
#define	_int_3210		PORTC,RC2
#define pcm_3210_pclk		LATA,LATA4
#define pcm_3210_drx		LATA,LATA3
#define pcm_3210_dtx		PORTA,RA2
#define pcm_3210_fsync		LATA,LATA1
